spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

#logging:
#  config: classpath:log4j2.xml

logging:
  level:
    org:
      springframework:
        web: DEBAG
      hibernate: INFO